import {
  ArrowLeftIcon,
  CheckCircledIcon,
  ReloadIcon,
} from "@radix-ui/react-icons";
import CATEGORY_META from "../../data/categoryMeta";
import CategoryBanner from "./CategoryBanner";
import PhaseTimeline from "./PhaseTimeline";
import HabitCard from "./HabitCard";

/**
 * TransformerDetail — full detail / preview view for a single transformer.
 * Composes CategoryBanner, PhaseTimeline, and HabitCard list.
 */
const TransformerDetail = ({
  transformer,
  onBack,
  onApply,
  applyLoading,
  onArchive,
  onEditHabit,
  onRemoveHabit,
  error,
}) => {
  const t = transformer;
  const sys = t.system || {};
  const catMeta = CATEGORY_META[sys.category] || CATEGORY_META.custom;
  const isPreview = t.status === "preview" || t.status === "draft";

  return (
    <div className="space-y-6 animate-fade-in">
      {/* Back */}
      <button
        onClick={onBack}
        className="flex items-center gap-2 text-sm font-spartan text-[var(--color-text-secondary)] hover:text-[var(--color-text-primary)] transition-colors"
      >
        <ArrowLeftIcon className="w-4 h-4" /> Back to transformers
      </button>

      {/* Category hero banner */}
      <CategoryBanner transformer={t} />

      {/* Phase timeline */}
      <PhaseTimeline transformer={t} />

      {error && (
        <p className="text-sm text-red-400 font-spartan">{error}</p>
      )}

      {/* Habits list */}
      <div className="space-y-3">
        <h3 className="text-xs font-spartan font-semibold text-[var(--color-text-secondary)] uppercase tracking-wider">
          {isPreview ? "Generated" : "Active"} Habits ({sys.habits?.length || 0})
        </h3>

        <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
          {sys.habits?.map((h, i) => (
            <HabitCard
              key={i}
              habit={h}
              index={i}
              isPreview={isPreview}
              canRemove={sys.habits.length > 1}
              onEdit={onEditHabit}
              onRemove={onRemoveHabit}
              accentColor={catMeta.accent}
            />
          ))}
        </div>
      </div>

      {/* Applied habits (active transformer) */}
      {t.status === "active" && t.appliedResources?.habitIds?.length > 0 && (
        <div className="p-5 rounded-2xl bg-[var(--color-surface-elevated)] border border-[var(--color-border-primary)]/20">
          <h3 className="text-xs font-spartan font-semibold text-[var(--color-text-secondary)] uppercase tracking-wider mb-4">
            Created Habits
          </h3>
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-2">
            {t.appliedResources.habitIds.map((h) => (
              <div
                key={h._id || h}
                className="flex items-center gap-3 p-3 rounded-xl bg-[var(--color-surface-hover)]/50"
              >
                <span className="text-lg">{h.icon || "🎯"}</span>
                <span className="text-sm font-spartan text-[var(--color-text-primary)]">
                  {h.name || "Habit"}
                </span>
                {h.isActive === false && (
                  <span className="text-[10px] text-[var(--color-text-tertiary)] font-spartan">
                    (archived)
                  </span>
                )}
              </div>
            ))}
          </div>
        </div>
      )}

      {/* Action bar */}
      {isPreview && (
        <div className="flex items-center gap-3 p-5 rounded-2xl glass-card-minimal">
          <button
            onClick={onApply}
            disabled={applyLoading}
            className="flex-1 h-12 bg-[var(--color-brand-600)] hover:bg-[var(--color-brand-700)] text-white rounded-xl text-sm font-spartan font-medium transition-all disabled:opacity-50 flex items-center justify-center gap-2 hover:shadow-lg hover:shadow-[var(--color-brand-600)]/20"
          >
            {applyLoading ? (
              <>
                <ReloadIcon className="w-4 h-4 animate-spin" /> Applying...
              </>
            ) : (
              <>
                <CheckCircledIcon className="w-4 h-4" /> Apply — Create{" "}
                {sys.habits?.length} Habits
              </>
            )}
          </button>
          <button
            onClick={() => onArchive(t._id)}
            className="h-12 px-6 rounded-xl text-sm font-spartan text-[var(--color-text-secondary)] hover:bg-[var(--color-surface-hover)] transition-colors"
          >
            Discard
          </button>
        </div>
      )}

      {/* Generation metadata */}
      {t.generation?.model && (
        <p className="text-xs text-[var(--color-text-tertiary)] font-spartan text-center pb-4">
          Generated by {t.generation.model} on{" "}
          {new Date(t.generation.generatedAt).toLocaleDateString()}
          {t.generation.tokenUsage?.input > 0 &&
            ` · ${
              t.generation.tokenUsage.input + t.generation.tokenUsage.output
            } tokens`}
        </p>
      )}
    </div>
  );
};

export default TransformerDetail;
